name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    if: false # TODO make it work
    strategy:
      matrix:
        os: [ubuntu-latest] # TODO, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'
          distribution: 'graalvm'

      - name: Build native image
        run: ./mill  graalvmnative # TODO

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}
          path: out/cli/native-image/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: Release with JReleaser
        run: # TODO mvn jreleaser:full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}