name: Release

on:
  push:
    tags: ['v*']

jobs:
  build-server:
    if: false # TODO make it work
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Build Server JAR
        run: |
          ./mill -i server.assembly
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
        # TODO version etc
          name: deder-server-v1.jar
          path: out/server/assembly.dest/out.jar
          overwrite: true

  # TODO add cli JAR too, why not..

  build-cli-native-image:
    if: false # TODO make it work
    strategy:
      matrix:
        os:
          - name: ubuntu-latest
            ext: ""
          - name: windows-latest
            ext: ".exe"
          # TODO macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build CLI native image
        run: |
          ./mill -i cli.nativeImage
          cp out/cli/nativeImage.dest/native-executable${{ matrix.os.ext }} deder
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deder-cli-${{ matrix.os.name }}
          path: deder${{ matrix.os.ext }}

  release-cli:
    if: false # TODO make it work
    needs: build-cli-native-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
      - name: Release with JReleaser
        run: echo "bla" # TODO mvn jreleaser:full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}